# This is a workflow which executes add_meetup_events.py every week to scrape the meeteup
# page: https://www.meetup.com/bostonpython/events/past/ to pull past events
# and create it's own event page under past-events and linked to a past-events/index.md

name: Update past-events page

# Controls when the workflow will run
on:
  # Run on a schedule
  #schedule:
  #  # Run at 2:05am early Sunday morning Eastern time (6/7:05 UTC)
  #  # https://crontab.guru/#5_7_*_*_0
  #  - cron: "5 7 * * 0"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: "${{ github.workflow }}-${{ github.ref }}"
  cancel-in-progress: true

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    name: "Update past events"

    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    permissions:
      contents: write # This will update pages in the repo

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
        with:
          persist-credentials: false

      - name: Set up Python
        uses: actions/setup-python@83679a892e2d95755f2dac6acb0bfd1e9ac5d548 # v6.1.0
        with:
          python-version: 3.8

      - name: Configure pip caching
        uses: actions/cache@9255dc7a253b0ccc959486e2bca901246202afeb # v5.0.1
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip wheel
          python -m pip install -r requirements.txt

      - name: Update past-events index
        run: |-
          ls -l past-events/index.md
          python add_meetup_events.py --rewrite
          ls -l past-events/index.md

      - name: Commit and push if  past-events/index.md changed
        run: |-
          git diff
          git config --global user.email "about-bot@example.com"
          git config --global user.name "about-bot"
          git diff --quiet || (git add -A && git commit -m "Update Past Events page")
          git push
